config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :groups, except: [:show] do
    resources :messages
  end
  get   'groups/search'  =>  'groups#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups
  has_many :users, through: :user_groups
  has_many :messages

  validates :name, presence: true

end

# has_manyは配列を期待している。から配列。

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :body, presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_groups
  #先に中間テーブルを定義して置かないと下のthroughが何を指しているのかわからなくなる。
  has_many :groups, through: :user_groups
  has_many :messages

  scope :search_like_name, ->(name){ where('name LIKE(?)', "%#{name}%") }
  # このnameはparams[:name]のname
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
  accepts_nested_attributes_for :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :replace_action, only: [:update,:edit]
  #renderメソッドは移動先のアクションの変数を持ってこなくてはならない。上記のreplace_actionはその変数をまとめたもの。
  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(post_params)
    if @group.save
       redirect_to :root, notice: "グループをさくせい"
    else
      @users = User.where.not(name: current_user.name)
      flash.now[:notice] = 'グループの作成にシッパイ'
      render :new
    end

  end

  def edit
    @users = User.where.not(name: current_user.name)
    # 補足ですが、コントローラーのインスタンス変数に@を付けるのは、単純に@が付いている変数がviewに渡されるというrailsの仕組みであるためです。
  end

  def update
    group = Group.find(params[:id])
      # / form_forタグに最初からupdateパスは埋め込まれている。すでにカラムが存在しているインスタンスならupdateアクションに自動的に振り分けられる。つまりパスを指定していたpictweetの<%= form_tag("/tweets/#{@tweet.id}", method: :patch ) do %>はform_forにおいてはいらないということになる
      if group.update(post_params)
        # flash.now[:notice]='グループを作成しました'
        redirect_to group_messages_path(group),notice: 'グループをさくせいしました'
      else
        flash.now[:notice]='グループの作成にシッパイ'
        render :edit
      # renderはbeforeアクションを呼ばない。だからbeforeアクションに記載していたコードを
      end
  end

  def search
    @users = User.search_like_name(params[:name])
    # userモデルにscopeを使ってwhere文を渡している。順番としてはjs→コントローラー→model→コントローラー→js
    respond_to do|format|
      format.json
    end
  end

  private

  def post_params
    params.require(:group).permit(:name, user_ids:[])
    # paramsの中身が"group"=>{"name"=>"ブルジョアソシエーション", "user_ids"=>["1", "2", "3", "4", "5", "2", "1"]}, "keyword"=>"", "commit"=>"Save"}なのでuser_idsは中身が配列になっているのでuser_ids[]
  end

  def replace_action
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :replace_post, only: [:index,:create]

  def index
    #このgroup_idは/groups/:group_id/messages(.:format)のgroup_idである。参照rake routes
    #group_idをとってくることによってそのグループの情報を取ってくることが出来る。そしてその情報からeditに飛べる。editに跳ぶにはここのindexの情報が必須だった。
    #ここはmessageコントローラーだが、普通に他のテーブルのモデル、例えば上でいうgroupモデルも取ってくる事が出来る。
    @messages = @group.messages.includes(:user)
    @message = Message.new

    respond_to do |format|
      format.html
      format.json {
        @messages = @group.messages.where('id > ?', params[:ID])
      }
    end

  end
# 過去の経験から未来を見出す
# 元々自分がどういう人間かということを考えて伝えながら
# 自分がどういう目的でサービスを作りたいか、（目的意識と交えながら）
#自分の軸を見つける。
#面白そうだったから
#未来を感じる。自分が興味がある最先端
  def create
    @messages = @group.messages.includes(:user)
    @message = current_user.messages.new(post_params)
    if @message.save
      respond_to do|format|
        format.html { redirect_to group_messages_path(@group), notice: "メッセージをさくせい" }
        format.json
        #  { render json: @message}がいらない理由はjbuilderで@messageを経由しているからいらない？
      end
    else
      flash.now[:notice] = 'メッセージの作成にシッパイ'
      render :index
    end
  end

  private

  def post_params
    # params.require(:message)はモデルから送られてくるキーの名前。モデル名ではない。でもモデル名ぽく書けばいいと思う。
    # params.require(:user).permit(:name, :email)」となっています。
    # これに対してform_forを使用したMoooviのparamsは、ハッシュの中にハッシュが存在する二重構造になっています。reviewというキーに対応する値そのものがハッシュだからです。そのハッシュの中には、カラム名がキーとなり、入力した情報が値として紐付いています。

    # このコードは「params が :user というキーを持ち、params[:user] は :name 及び :email というキーを持つハッシュであること」を検証します。

    # 例えば、params[:user] が {:name => 'taro', :email => 'taro@example.com'} のようなハッシュである場合に検証 OK となります。

    params.require(:message).permit(:body, :image).merge(group_id: params[:group_id])
  end

  def replace_post
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/common/_flash.html.haml
- flash.each do |name, msg|
  = content_tag :div, msg, class: "flash flash__#{name}"

app/views/groups/_group.html.haml
.left-content__group-content
  .left-content__group-name
    %p
      = link_to group.name, group_messages_path(group)
      .left-content__group-text
        %p 回せ

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = form_for @group do |f|
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_name"} グループ名
      .chat-group-form__field--right
        = f.text_field :name, id:"chat_group_name", class:"chat-group-form__input", placeholder: "グループ名を入力してください"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      /   %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
      / .chat-group-form__field--right
      /   .chat-group-form__search.clearfix
      /     %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
      /   #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
      .chat-group-form__field.clearfix
        %p.chat-group-user__name
          .check_box
            = f.collection_check_boxes(:user_ids, @users, :id, :name) do |b|
              = b.label class:"label-checkbox" do
                = b.label { b.check_box + b.text }
        .chat-group-form__field--left
        .chat-group-form__field--right
          = f.submit class: "chat-group-form__action-btn", "data-disable-with" => "Save", name: "commit", type: "submit", value: "Save"

app/views/groups/index.html.haml
.left-content
  .left-content__user
    %p
      = current_user.name
    %span.left-content__user-mark1
      = link_to new_group_path do
        %i.fa.fa-external-link
    %span.left-content__user-mark2
      = link_to edit_user_registration_path do
        %i.fa.fa-cog
  .left-content__group
    .left-content__group-content
      = render partial: "messages/group", collection: @groups

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  .chat-group-form__field.clearfix
    = form_for @group do |f|
      .chat-group-form__field--left
        %label.chat-group-form__label{:for => "chat_group_name"} グループ名
      .chat-group-form__field--right
        = f.text_field :name, id:"chat_group_name", class:"chat-group-form__input", placeholder: "グループ名を入力してください"
      .chat-group-form__field.clearfix
        .chat-group-form__field--left
          %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
        .chat-group-form__field--right
          .chat-group-form__search.clearfix
            %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text", :name =>"keyword"}/
          %ul#user-search-result
      .chat-group-form__field.clearfix
        .chat-group-form__field--left
          %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
        .chat-group-form__field--right
          %ul.chat-group-user.js-users
            = current_user.name
          %input{:type => "hidden", :name => "group[user_ids][]", :value => current_user.id}
      .chat-group-form__field.clearfix
        .chat-group-form__field--left
        .chat-group-form__field--right
          = f.submit class: "chat-group-form__action-btn", "data-disable-with" => "Save", name: "commit", type: "submit", value: "Save"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render partial: "common/flash"
    = yield

app/views/messages/_message.html.haml
.chat{ "data-message-id": "#{message.id}"}

  .right-content__chat-name
    %p
      = message.user.name
      /おそらくrender @messagesとしたときにインスタンス名がmessageとなった？
  .right-content__chat-time
    %p
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
  .right-content__chat-text
    %p
      = message.body
  .right-content__chat-image
    %p
      = image_tag message.image.thumb.url if message.image.url
/ この記述をｊｓに同じように書いているのに、ここに書く必要があるのかという疑問に関して、jsはあくまで一時的にhtmlを表示するだけなのでリーロードすると消えてしまう。そのためにhtmlが必要だった。
/ data-~にしておくとdataを取り扱っていることになる。data-message-idはdataをidに振り分けていることになる。

app/views/messages/index.html.haml
.top-content
.left-content
  .left-content__user
    %p
      = current_user.name
    %span.left-content__user-mark1
      = link_to new_group_path do
        %i.fa.fa-external-link
    %span.left-content__user-mark2
      = link_to edit_user_registration_path do
        %i.fa.fa-cog
  .left-content__group
    .left-content__group-content
      = render current_user.groups
.right-content
  .right-content__name
    .right-content__name-element
      .right-content__name-element-group
        %p
          = @group.name
      .right-content__name-element-user
        %p
          = @group.users.pluck(:name).join(' ')
    .right-content__name-edit
      = link_to edit_group_path(@group) do
        %p.right-content__name-edit-element edit
  .right-content__chat
    = render @messages
  .right-content__message
    = form_for [@group, @message] do |f|
      = f.text_area :body, placeholder: "グループ名を入力してください"
      = f.label :image, class: 'chat-file' do
        = f.file_field :image, class: "image"
        %i.fa.fa-image
      = f.submit "send", class:"right-content__message-button"